PACKAGE_NAME="amneziawg"
PACKAGE_VERSION="0.0.0"
AUTOINSTALL=yes
REMAKE_INITRD=yes

MAKE="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

BUILT_MODULE_NAME="amneziawg"
DEST_MODULE_LOCATION="/kernel/net"